version: '3'
services:
  vaadin-demo:
    image: postgres:13.7
    platform: linux/x86_64
    restart: always
    environment:
      POSTGRES_USER: 'vaadinstart'
      POSTGRES_PASSWORD: 'vaadinstart'
      POSTGRES_DB: 'vaadinstart'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '15432:5432'
    expose:
      # Opens port 3306 on the container
      - '15432'
      # Where our data will be persisted
    volumes:
      - vaadin-demo-volume:/var/lib/postgresql/data
volumes:
  vaadin-demo-volume:
